INSERT INTO movies (
    title,
    original_title,
    overview,
    release_date,
    runtime_minutes,
    genres,
    director,
    cast_members,
    poster_url,
    vote_average,
    vote_count,
    popularity,
    external_id,
    external_source
) VALUES
(
    'Inception',
    'Inception',
    'A thief who steals secrets through dream-sharing technology is offered a chance to plant an idea instead.',
    '2010-07-16',
    148,
    ARRAY['Sci-Fi', 'Thriller', 'Action'],
    'Christopher Nolan',
    ARRAY['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    NULL,
    8.8,
    2200000,
    85.5,
    '27205',
    'tmdb'
),
(
    'The Matrix',
    'The Matrix',
    'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
    '1999-03-31',
    136,
    ARRAY['Sci-Fi', 'Action'],
    'Lana Wachowski',
    ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    NULL,
    8.7,
    1800000,
    80.0,
    '603',
    'tmdb'
),
(
    'Interstellar',
    'Interstellar',
    'Explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
    '2014-11-07',
    169,
    ARRAY['Sci-Fi', 'Drama', 'Adventure'],
    'Christopher Nolan',
    ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    NULL,
    8.6,
    1900000,
    78.0,
    '157336',
    'tmdb'
),
(
    'The Shawshank Redemption',
    'The Shawshank Redemption',
    'Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.',
    '1994-09-23',
    142,
    ARRAY['Drama'],
    'Frank Darabont',
    ARRAY['Tim Robbins', 'Morgan Freeman'],
    NULL,
    9.3,
    2600000,
    95.0,
    '278',
    'tmdb'
),
(
    'Parasite',
    'Parasite',
    'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy and destitute.',
    '2019-05-30',
    132,
    ARRAY['Thriller', 'Drama', 'Comedy'],
    'Bong Joon-ho',
    ARRAY['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    NULL,
    8.5,
    900000,
    70.0,
    '496243',
    'tmdb'
),
(
    'Spirited Away',
    'Spirited Away',
    'A young girl enters a world ruled by gods and witches where humans are changed into beasts.',
    '2001-07-20',
    125,
    ARRAY['Animation', 'Fantasy', 'Family'],
    'Hayao Miyazaki',
    ARRAY['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
    NULL,
    8.6,
    1100000,
    72.0,
    '129',
    'tmdb'
),
(
    'The Dark Knight',
    'The Dark Knight',
    'Batman must accept one of the greatest psychological tests to fight the injustice brought by the Joker.',
    '2008-07-18',
    152,
    ARRAY['Action', 'Crime', 'Drama'],
    'Christopher Nolan',
    ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    NULL,
    9.0,
    2500000,
    88.0,
    '155',
    'tmdb'
),
(
    'La La Land',
    'La La Land',
    'A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles.',
    '2016-12-09',
    128,
    ARRAY['Romance', 'Drama', 'Music'],
    'Damien Chazelle',
    ARRAY['Ryan Gosling', 'Emma Stone'],
    NULL,
    8.0,
    1200000,
    65.0,
    '313369',
    'tmdb'
);
