"""initial

Revision ID: 58ae8a670cc7
Revises: 
Create Date: 2026-07-08 13:57:28.193717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '58ae8a670cc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'recommended_movie_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.drop_index(op.f('idx_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chats_user_id'), table_name='chats')
    op.drop_index(op.f('idx_movies_genres'), table_name='movies', postgresql_using='gin')
    op.drop_index(op.f('idx_movies_release_date'), table_name='movies')
    op.drop_index(op.f('idx_movies_title'), table_name='movies', postgresql_using='gin')
    op.drop_constraint(op.f('movies_external_source_external_id_key'), 'movies', type_='unique')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('movies_external_source_external_id_key'), 'movies', ['external_source', 'external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_movies_title'), 'movies', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('idx_movies_genres'), 'movies', ['genres'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_chat_id'), 'chat_messages', ['chat_id', 'created_at'], unique=False)
    op.alter_column('chat_messages', 'recommended_movie_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True,
               existing_server_default=sa.text("'{}'::uuid[]"))
    # ### end Alembic commands ###
